# Nome da aplicação
spring.application.name=devshowcase-api

# Perfil padrão ativo quando rodar localmente
spring.profiles.active=dev

# Configurações do Banco H2 (em memória)
spring.datasource.url=jdbc:h2:mem:devshowcasedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar Console Web do H2 (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate / JPA para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Caminho personalizado para aceder à interface visual do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs